// Package openapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapigen

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Payment defines model for Payment.
type Payment struct {
	Amount    *string    `json:"amount,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *string    `json:"id,omitempty"`
	Merchant  *string    `json:"merchant,omitempty"`
	Status    *string    `json:"status,omitempty"`
}

// User defines model for User.
type User struct {
	Email *string `json:"email,omitempty"`
	Role  *string `json:"role,omitempty"`
	Token *string `json:"token,omitempty"`
}

// Sort defines model for sort.
type Sort = string

// LoginResponse defines model for LoginResponse.
type LoginResponse = User

// PaymentListResponse defines model for PaymentListResponse.
type PaymentListResponse struct {
	Payments *[]Payment `json:"payments,omitempty"`
	Total    *int       `json:"total,omitempty"`
}

// PaymentSummaryResponse defines model for PaymentSummaryResponse.
type PaymentSummaryResponse struct {
	Completed   *int     `json:"completed,omitempty"`
	Failed      *int     `json:"failed,omitempty"`
	Processing  *int     `json:"processing,omitempty"`
	Total       *int     `json:"total,omitempty"`
	TotalAmount *float32 `json:"total_amount,omitempty"`
}

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = Error

// PostDashboardV1AuthLoginJSONBody defines parameters for PostDashboardV1AuthLogin.
type PostDashboardV1AuthLoginJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetDashboardV1PaymentsParams defines parameters for GetDashboardV1Payments.
type GetDashboardV1PaymentsParams struct {
	// Sort Comma-separated sort fields. Common patterns: `-created_at` (prefix `-` = desc) `amount` (no prefix `-` = asc)
	Sort *Sort `form:"sort,omitempty" json:"sort,omitempty"`

	// Status status of payment (completed , processing , or failed)
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// Page page number (starting from 1)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit limit of items per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostDashboardV1AuthLoginJSONRequestBody defines body for PostDashboardV1AuthLogin for application/json ContentType.
type PostDashboardV1AuthLoginJSONRequestBody PostDashboardV1AuthLoginJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with email + password
	// (POST /dashboard/v1/auth/login)
	PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request)
	// List of payments
	// (GET /dashboard/v1/payments)
	GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams)
	// Payments summary
	// (GET /dashboard/v1/payments/summary)
	GetDashboardV1PaymentsSummary(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login with email + password
// (POST /dashboard/v1/auth/login)
func (_ Unimplemented) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List of payments
// (GET /dashboard/v1/payments)
func (_ Unimplemented) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Payments summary
// (GET /dashboard/v1/payments/summary)
func (_ Unimplemented) GetDashboardV1PaymentsSummary(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostDashboardV1AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDashboardV1AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1Payments operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardV1PaymentsParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1Payments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1PaymentsSummary operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1PaymentsSummary(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1PaymentsSummary(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dashboard/v1/auth/login", wrapper.PostDashboardV1AuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/payments", wrapper.GetDashboardV1Payments)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/payments/summary", wrapper.GetDashboardV1PaymentsSummary)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xWS2/bRhD+K4ttDzZKm1STQ0CgB/cVpHAAo6nbg2vEa3Ikbcp9ZHboWDX034vZpURK",
	"pGonLppLLM7jm29eOw+ycsY7C5aCLB+kV6gMEGD8FRwS/19DqFB70s7KUv7gjFEnAViXoBasJeYamjqc",
	"ChY6K7wiArShFDcnFQLrvVd0I448wlzfi5uTG/GdYL/H4kYZ11oWWid25CpUx39amUnNuB9bwJXMpFUG",
	"ZJmCy2SolmAURwn3yviGRQNImUla+ahPqO1CrtfrTCIE72yAyPLcLbT9tfvCHypnCWxkrrxvdKWYef4h",
	"MP2HAeLXCHNZyq/yPol5kob8MgAmsN3sIVCLVpD7C6xQthZtABTazh2aiCPXmbxQKwOWznWgLwrMo/OA",
	"pKEravQW/9YEJjwWewfPkXTJU4hqFX87Ug3bdwJtCRaR6VbX3X6Aiqa4d34F8xrQfNcao3D1HzBlLg0Q",
	"1FMRZnKudHNI5tFVEAK3yKT8IPFO9D518UDDtub2czPTpYK9XlrV0tKh/hvqnxAdPiEv3QjEXLTRHiyx",
	"UmIdOu+lfKsjVeG49e5Uo+vUkTKTd6ppuxrUIMuXxSyTBkJQC6Zwueu1FOaQp8jyabOS6E2k5azH0s6K",
	"VD+G2qBWCDUrqCbIHi/y3+Zsv0Vq2NkWkeC4qFvKw8XydPbjtcNb52OrkUtxlcLoUa5HPbKdjjGFvtP6",
	"yGYF/xvDZnKwC8sHmdaMLGWtCE5IG5iy0fWe9yklA1gt1X4gb7uv4mzKJpCiNuxabIdWZKKfQpFxUruJ",
	"ncrmKF9x446SBUbp4dz2saBrYFKQKjiWTAxyJgNULWpavePOS5C3oBCQe7f/9fMm77/88dvm1WJPSdoT",
	"XBL5NAn8JMQgNKXErl67c2UXZ96Ls4s3PKmAIc3J7LQ4LTh058Eqr2UpX5wWpy9kJr2iZYwqr1VY3jqF",
	"dX43y7mP84ZfvpgyF2IZOXFx1N7UvJRcoB83Rr/PmFB8K2VqZQj0vatXz1jXh2vjVQifHNbTVRgOUvIx",
	"sLieXLe9CWEL+yfAt0VxaEdt9fLdO2GdyZfF7HGr8RqPXbPdxNGr+KRpKSIV8Y3YUmHN3bINn/IFTNTs",
	"NQxLdrFRz3Yuu6vpoHuVPB5X62z/9EvjK9xcdIGIo8en9/jQAZd2wfCRGJV6PwCvFiDSwyqOAikkBpuj",
	"M2J2CIdtdlBqmKu2IVnyy6atNq2Jf49Pmn34RhtNTD+eUcIDis77FHDUPoBcZNKo+w66KB4J5PpL+nXq",
	"iHxm13a7LnbQcMtdXXOIg6bWgQZdEv6lk/Ot1Wd19OZQekZi9s/O/yk3GwZi8ykdSoB3m9lsselegjLP",
	"G1epZukCla+KV4VcX6//CQAA//+khsp3tA0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
